In [1]:
import numpy as np

## Creando un array de una dimension

In [2]:
lista = [1,2,3,4]

In [3]:
array = np.array(lista)

In [4]:
array

array([1, 2, 3, 4])

## array de 2 dimensiones (matriz)

In [5]:
lista2 = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
lista2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
array2 = np.array(lista2)

In [8]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Arrays, arange, zeros, ones, linspace , eye

In [9]:
array = np.arange(5) 

In [10]:
array

array([0, 1, 2, 3, 4])

## numpy tiene una funcion (arange) para generar un array con numeros.

In [11]:
np.arange(2,10) 

array([2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(6,40,2)  #de 2 en 2

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

## Zeros
> genera matrices con 0.

In [13]:
np.zeros(3) #genera un array con 3 elementos en 0

array([0., 0., 0.])

In [14]:
np.zeros((3,4)) #array de 2 dimensiones,con 3 filas y 4 columnas

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
#lo de zeros aplica tambien para np.ones

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Linspace
> genera una matriz con numeros que van de un punto a otro, especificando un final.

In [18]:
np.linspace(5,8,50) #de 5 hasta 8 y 50 elementos entre el 5 y el 8

array([5.        , 5.06122449, 5.12244898, 5.18367347, 5.24489796,
       5.30612245, 5.36734694, 5.42857143, 5.48979592, 5.55102041,
       5.6122449 , 5.67346939, 5.73469388, 5.79591837, 5.85714286,
       5.91836735, 5.97959184, 6.04081633, 6.10204082, 6.16326531,
       6.2244898 , 6.28571429, 6.34693878, 6.40816327, 6.46938776,
       6.53061224, 6.59183673, 6.65306122, 6.71428571, 6.7755102 ,
       6.83673469, 6.89795918, 6.95918367, 7.02040816, 7.08163265,
       7.14285714, 7.20408163, 7.26530612, 7.32653061, 7.3877551 ,
       7.44897959, 7.51020408, 7.57142857, 7.63265306, 7.69387755,
       7.75510204, 7.81632653, 7.87755102, 7.93877551, 8.        ])

## Eye
> genera una matriz cuadra, con el mismo numero en filas y columnas.

In [19]:
np.eye(5) #5 filas y 5 columnas, los elementos intermedios son 1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Arrays - numeros aleatorios - rand y randn


## Rand
> Genera numeros aleatorios del 0 al 1

In [20]:
np.random.rand(5)

array([0.30148895, 0.95923378, 0.86069456, 0.54673857, 0.33856239])

> Dos dimensiones:

In [21]:
np.random.rand(2,3)

array([[0.71643846, 0.03817908, 0.02423344],
       [0.83754074, 0.6856679 , 0.48855519]])

## Randn
> incluye negativos y positivos sin limite (osae que no va de 0 a 1).

## Numeros aleatorios enteros

* Randint -> Necesita 2 parametros el primero es desde donde y el segundo hasta donde va a hacer el random.
             Tambien, se le puede asignar un 3er parametro para establecer una cantidad de numeros aleatorios.

In [22]:
np.random.randint(1,4) 

2

In [23]:
np.random.randint(1,20,5)  #5 numeros aleatorios del 1 al 20

array([ 5,  1, 10,  5, 16])

## Cambiar tamaño de los array con Reshape

In [24]:
array = np.random.randint(1,100,25)

In [25]:
array

array([58, 16, 95,  1, 99, 84, 84, 97, 75, 81, 98, 30,  5, 71, 26, 57, 73,
       19, 17, 36, 12, 53, 20, 11, 52])

In [26]:
matriz = array.reshape(5,5) 
#para utilizar el reshape, se le debe asignar la cantidad de filas y columnas respectivas a la cantidad de numeros.

In [27]:
matriz

array([[58, 16, 95,  1, 99],
       [84, 84, 97, 75, 81],
       [98, 30,  5, 71, 26],
       [57, 73, 19, 17, 36],
       [12, 53, 20, 11, 52]])

In [28]:
matriz = np.random.randint(1,100,21).reshape(3,7) 

In [29]:
matriz

array([[26, 53, 26, 35, 79, 81,  5],
       [ 5, 91, 47, 59, 45, 19,  7],
       [90, 97, 94, 10,  9,  9, 92]])

## Max y Min

In [30]:
array = np.random.randint(1,100,50)

In [31]:
array

array([85, 45, 96, 16, 28, 69, 22, 50, 53, 20, 11, 50, 24, 73, 39, 57, 60,
       87, 51, 16, 42, 61, 75, 45, 96, 53, 32, 87, 63, 82, 53, 34, 29, 36,
       98, 45, 51, 68, 32, 99, 30, 21, 63, 44, 48, 99,  2, 97, 40, 17])

In [32]:
valor_maximo = array.max()
valor_maximo

99

In [33]:
posicion_valor_maximo = array.argmax()
posicion_valor_maximo

39

In [34]:
valor_minimo = array.min()
valor_minimo

2

In [35]:
posicion_valor_minimo = array.argmin()
posicion_valor_minimo

46

# Indexación en arrays
> indexación -> acceder a los elementos de forma individual.

In [36]:
import numpy as np

In [37]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
array[0]

0

In [39]:
array[-1] #ultima posición

9

In [40]:
array[2:4] # de la 2 a la 4 - 1

array([2, 3])

In [41]:
array[:] #todo el array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
array[5:] #de la pos 5 a la final

array([5, 6, 7, 8, 9])

In [43]:
array[:4] #del inicio al 4 - 1

array([0, 1, 2, 3])

### copias del array

In [44]:
array2 = array.copy()
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Indexación en 2 dimensiones

In [45]:
array = np.array([[1,2,3],[3,4,6],[7,8,9]])
array

array([[1, 2, 3],
       [3, 4, 6],
       [7, 8, 9]])

In [46]:
array[0]

array([1, 2, 3])

In [47]:
array[:2]

array([[1, 2, 3],
       [3, 4, 6]])

In [48]:
array[0][0] #primera fila y primera columna

1

In [49]:
array[0,0] #primera fila y primera columna

1

## Seleccionar elementos de un array según una condición.

In [50]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
condicion = array > 5
condicion

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [52]:
array[condicion]

array([6, 7, 8, 9])

In [53]:
arrayConCondicion = array[condicion]

In [54]:
arrayConCondicion

array([6, 7, 8, 9])

In [55]:
array[array<6]

array([0, 1, 2, 3, 4, 5])

In [56]:
array[ array % 2 == 0] #todos los pares

array([0, 2, 4, 6, 8])

## Operaciones sobre los Arrays

In [57]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [59]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
array * 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [61]:
array -1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [62]:
array2 = np.arange(5,15)
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
array2 + array

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [64]:
np.sqrt(array2) #raiz cuadrada de cada elemento del array2

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

# Ejercicios
> crear una lista de numeros secuenciales de 10 a 39.

> convertir la lista en una matriz de 2 dimensiones (3 filas x 10 columnas)

> mostrar en pantalla el valor de la esquina superior derecha

In [65]:
lista = np.arange(10,40)
lista

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [66]:
matriz_de_dos_dimensiones = lista.reshape(3,10)
matriz_de_dos_dimensiones

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [67]:
print("Valor de la ezquina superior derecha: "+ str(matriz_de_dos_dimensiones[0,-1]))

Valor de la ezquina superior derecha: 19


> Crea un array de una dimension con 9 valores enteros aleatorios entre 0 y 100.
> Convierte ese array en una matriz de 2 dimensiones, 3 filas y 3 columnas.
> Muestra en pantalla el valor del elemento de la matriz de la esquina inferior derecha.

In [68]:
lista_ejer_2 = np.random.randint(0,100,9)
lista_ejer_2

array([97, 80, 56, 95, 81, 96, 53, 10, 67])

In [69]:
lista_ejer_2 = lista_ejer_2.reshape(3,3)
lista_ejer_2

array([[97, 80, 56],
       [95, 81, 96],
       [53, 10, 67]])

In [70]:
print("valor del elemento de la matriz de la esquina inferior derecha: "+ str(lista_ejer_2[-1,-1]))

valor del elemento de la matriz de la esquina inferior derecha: 67
