# arbol de decision - clasificacion 

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [2]:
#de mdlada.io descargamos la base de datos wine(Vinos)

In [3]:
ls

 El volumen de la unidad C no tiene etiqueta.
 El número de serie del volumen es: 9C30-9931

 Directorio de C:\Users\erik_\Curso-IA-Udemy\Arbol de decisiones

04/08/2021  22:07    <DIR>          .
04/08/2021  22:07    <DIR>          ..
04/08/2021  22:07    <DIR>          .ipynb_checkpoints
04/08/2021  22:07                72 Untitled.ipynb
04/08/2021  22:04            12.895 vino.csv
               2 archivos         12.967 bytes
               3 dirs  53.470.412.800 bytes libres


In [7]:
vinos = pd.read_csv('vino.csv')

In [8]:
vinos.head()

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280/OD315 of diluted wines  Proline Wine Type  
0                          3.92   1065.0       One  
1                          3.40   1050.0       One  
2                          3.17   1185.0       One  
3                          3.45   1480.0       One  
4                          2.93    735.0       One

In [9]:
vinos["Wine Type"].unique()

array(['One', 'Two', 'Three'], dtype=object)

In [10]:
vinos["Wine Type"].value_counts()

Two      71
One      59
Three    48
Name: Wine Type, dtype: int64

In [13]:
X = vinos.drop('Wine Type',axis=1)

In [14]:
X

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280/OD315 of diluted wines  Proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [19]:
y = vinos["Wine Type"] #vino a predecir, la Y es el objetivo
y

0        One
1        One
2        One
3        One
4        One
       ...  
173    Three
174    Three
175    Three
176    Three
177    Three
Name: Wine Type, Length: 178, dtype: object

In [42]:
from sklearn.model_selection import train_test_split

In [50]:
X_train , X_test, Y_train, Y_test = train_test_split(X,y, test_size=0.3, random_state=45)

In [51]:
from sklearn.tree import DecisionTreeClassifier

In [52]:
arbol = DecisionTreeClassifier()

In [53]:
arbol.fit(X_train,Y_train)

DecisionTreeClassifier()

In [54]:
predicciones = arbol.predict(X_test)
predicciones

array(['Three', 'Three', 'One', 'Two', 'Two', 'Two', 'Three', 'One',
       'One', 'Two', 'Two', 'One', 'One', 'Three', 'Three', 'Two', 'Two',
       'Three', 'Three', 'Three', 'Two', 'Two', 'One', 'Three', 'Three',
       'Three', 'One', 'Two', 'Three', 'Three', 'Three', 'Three', 'Three',
       'One', 'Two', 'Three', 'One', 'One', 'Two', 'One', 'Two', 'Two',
       'Two', 'Two', 'Two', 'Three', 'Three', 'Three', 'One', 'Two',
       'One', 'One', 'Three', 'One'], dtype=object)

In [55]:
 from sklearn.metrics import classification_report, confusion_matrix

In [56]:
print(classification_report(Y_test, predicciones))

              precision    recall  f1-score   support

         One       1.00      0.94      0.97        16
       Three       0.90      0.95      0.93        20
         Two       0.89      0.89      0.89        18

    accuracy                           0.93        54
   macro avg       0.93      0.93      0.93        54
weighted avg       0.93      0.93      0.93        54



In [57]:
print(confusion_matrix(Y_test, predicciones))

[[15  0  1]
 [ 0 19  1]
 [ 0  2 16]]
